config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
 
resources :available_spaces

namespace :admin do
    resources :available_spaces
    match '/show_available_space' => 'available_spaces#show_available_space'
  end

end

app/models/available_space.rb
class AvailableSpace < ActiveRecord::Base
  # attr_accessible :title, :body

  def self.total_aval_space
   	OrderSetting.last.maximum_space
  end	
end

app/controllers/spree/admin/available_spaces_controller.rb
class Spree::Admin::AvailableSpacesController <  Spree::Admin::BaseController

  before_filter :fetch_bookings_details ,:only => [:index,:show_available_space]


  def index 
                  
  end 

  def show_available_space
          
  end   

  protected

    def fetch_bookings_details
      @bookings_data = {}
      @booking_rate = []
      start_date = ((params[:search].blank? ? Time.now.beginning_of_month : (params[:search][:start_date].blank? ? Time.now.beginning_of_month : params[:search][:start_date]))).to_date.strftime("%Y-%m-%d")
      end_date = ((params[:search].blank? ? Time.now.end_of_month : (params[:search][:end_date].blank? ? Time.now.end_of_month : params[:search][:end_date])) ).to_date.strftime("%Y-%m-%d")

      if Rails.env == "development"
      @bookings = Spree::Booking.find_by_sql("SELECT IFNULL(sum( rating ),0) as total_space,filter_date.id as day FROM spree_bookings RIGHT JOIN (select adddate(\"#{start_date}\", numslist.id) as id from (SELECT n1.col_i + n10.col_i*10 + n100.col_i*100 AS id FROM nums n1 cross join nums as n10 cross join nums as n100) as numslist where adddate(\"#{start_date}\", numslist.id) <= \"#{end_date}\" ) filter_date ON (filter_date.id between DATE_FORMAT(spree_bookings.pickup_date,'%Y-%m-%d') and DATE_FORMAT(spree_bookings.delivery_date ,'%Y-%m-%d')  ) GROUP BY filter_date.id")  
      #@bookings = Spree::Booking.find_by_sql("SELECT IFNULL(sum( rating ),0) as total_space,filter_date.id as day FROM spree_bookings RIGHT JOIN (select adddate(\"#{start_date}\", numslist.id) as id from (SELECT n1.col_i + n10.col_i*10 + n100.col_i*100 AS id FROM nums n1 cross join nums as n10 cross join nums as n100) as numslist where adddate(\"#{start_date}\", numslist.id) <= \"#{end_date}\" ) filter_date ON (DATE_FORMAT(spree_bookings.pickup_date,'%Y-%m-%d') = filter_date.id) GROUP BY filter_date.id")
      else
      @bookings = Spree::Booking.find_by_sql "SELECT  filter_date.id::date as day,coalesce(sum(spree_bookings.rating),0) as total_space FROM  spree_bookings  RIGHT JOIN ( select '#{start_date}'::date + cast(numlist.id::text || ' days' as interval) as  id  from (SELECT n1.col_i + n10.col_i*10 + n100.col_i*100 AS id  FROM nums n1 cross join nums as n10 cross join nums as n100) as numlist where (select '#{start_date}'::date + cast(numlist.id::text || ' days' as interval)) <= '#{end_date}'::date ) filter_date ON (filter_date.id between spree_bookings.pickup_date::date  and spree_bookings.delivery_date::date) GROUP BY filter_date.id" 

      end        
      @bookings.each do |booking|  
        @bookings_data[booking.day.to_s] = booking.total_space.to_i
      end unless @bookings.blank?
    end

        
end

app/helpers/available_spaces_helper.rb
module AvailableSpacesHelper
end

app/views/spree/admin/available_spaces/index.html.erb
<%= form_tag admin_available_spaces_path ,:method=>"get" do %>
  <p>
    <p>Start Date
    <%= text_field_tag("search[start_date]", !params[:search].blank? && !params[:search]["start_date"].blank? ?  params[:search]["start_date"] : "", :class => 'datepicker')  %>
    
     End Date 
    <%= text_field_tag( "search[end_date]", !params[:search].blank? && !params[:search]["end_date"].blank? ?  params[:search]["end_date"] : "" , :class => 'datepicker') %>
    <%= submit_tag "Search", :name => nil %>
  </p>
 <% end %>
 <div id="chart_div" style="width: 1200px; height: 500px;"></div>

  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable(
          <%=raw @bookings_data.to_a%>
        );

        var options = {
          title: 'Space Availability Report',
          hAxis: {title: 'Days', titleTextStyle: {color: 'red'}},
          vAxis:{title:'Occupied Space', maxValue: <%= AvailableSpace.total_aval_space %>}
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>


<%= button_link_to "Textual Overview of Space Availability",admin_show_available_space_path%>

app/views/spree/admin/available_spaces/show_available_space.html.erb
<%= form_tag admin_show_available_space_path ,:method=>"get" do %>
  <p>
    <p>Start Date
    <%= text_field_tag("search[start_date]", !params[:search].blank? && !params[:search]["start_date"].blank? ?  params[:search]["start_date"] : "", :class => 'datepicker')  %>
    
     End Date 
    <%= text_field_tag( "search[end_date]", !params[:search].blank? && !params[:search]["end_date"].blank? ?  params[:search]["end_date"] : "" , :class => 'datepicker') %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<table>
	<tr>
		<th>Date</th>
		<th>Space</th>
	</tr>
<% @bookings_data.each do |date,space| %>
<tr>
	<td><b><%= date %></b></td>
	<td><b><%= space %></b></td>

</tr>
<% end %>
</table>

<%= button_link_to "Graphical Overview of Space Availability",admin_available_spaces_path%>